/**
 * Every command a human is meant to type must be written down somewhere a human will look.
 *
 * ## Why this is a test and not a habit
 *
 * A command nobody can find is a command nobody runs, which is this repo's own most-repeated failure —
 * *"a check that exists and does not run"* — arriving through discoverability rather than through
 * automation. It is also the reason `capture-check` was mandatory and never ran once, and why
 * `release:gate` was broken from the day it was written.
 *
 * Measured on 2026-08-25: three commands and two flags were added in one day (`fleet:provision`,
 * `lab:inventory`, `lab:pipeline`, `--serial`, `--allow-stale-workers`) and only one of them reached
 * CLAUDE.md. The other two were discoverable solely by reading their own source, which is the same
 * "somebody has to remember" that this repo removes everywhere else. That is what this stops.
 *
 * ## TWO POPULATIONS, TWO STANDARDS -- and #478 (A6b) moved one of them from prose to a generated page
 *
 * `package.json`'s npm scripts stay documented **in the context of the problem they solve** — hand-written
 * prose, checked only for COVERAGE (is the name mentioned somewhere a human would look), never generated.
 * `docs/coverage.md` already showed that generating a table works for a table of criteria and would be
 * wrong here: nothing can generate the REASON a command exists.
 *
 * `scripts/*.mjs` commands are the opposite problem. A3 (#454) measured **24 runnable scripts with no
 * `package.json` entry, 20 of them undocumented** — invisible to the OLD version of this test, which read
 * `package.json` and prose alone. A5's `commands.mjs` catalogue closed the NAMING half (a script gets a
 * name without editing `package.json`); this closes the DOCUMENTATION half: every script that is a real
 * command (see `commandScripts()` in `generate-commands-doc.mjs`, derived from the same entry-point-guard
 * signal `entry-points.test.ts` already pins, never a hand list) MUST carry a `// command:` header, and
 * `docs/commands.md` is generated from those headers and checked against the tree. A script with no header
 * fails this test outright — the exact shape CLAUDE.md's own registries rule asks for: *"the list nobody
 * maintains is the list that cannot go stale."*
 *
 * `docs/commands.md` is deliberately COMMITTED AND CHECKED, not gitignored -- #459 (A7) says a generated
 * file is never tracked, and this is the stated exception: a reader wants to browse the command list on
 * GitHub, so untracking it would trade that for nothing this row's population needs. The file DOES carry
 * #459's `<!-- GENERATED by ... -->` marker -- it is a real generated file -- and is named explicitly in
 * `generated-paths.test.ts`'s own `TRACKED_EXEMPT` map, with the reason above, so that guard KNOWS this
 * file is tracked on purpose rather than simply failing to see it. See `generate-commands-doc.mjs`'s own
 * header for why the exemption belongs there rather than in an omitted marker.
 */
/**
 * #954: THE CROSS-REFERENCE HALF OF THIS FILE IS OFF THE PULL-REQUEST PATH. `commands-documented`'s rule now runs
 * once a night, in `scripts/doc-cross-reference-report.mjs`, which imports the same module this file
 * does -- so nothing about the rule changed, only when it runs and what a disagreement costs. See #905
 * for the argument and #954 for the retirement, which waited until the first nightly report had posted.
 *
 * WHAT STAYS HERE is what that report does not assert: the `// command:` header rule (#908's), its four mutation cases, and the honesty of the INTERNAL list -- none of which is a cross-reference.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = fileURLToPath(new URL("../../../../", import.meta.url));

import { commandScripts, commandHeader } from "../../../../scripts/generate-commands-doc.mjs";
// #905: the prose-coverage and page-freshness halves live in the doc cross-reference check the nightly report
// also runs -- one copy. The `// command:` header rule and the MUTATION cases below stay here.
import {
  INTERNAL, npmScripts as npmScriptsIn,
} from "../../../../scripts/doc-checks/commands-documented.mjs";

const npmScripts = () => npmScriptsIn(REPO);

test("the internal list is honest: every entry is a real npm script", () => {
  // An allowlist that outlives its entries is a hole nobody can see.
  const scripts = new Set(npmScripts());
  for (const [name, why] of Object.entries(INTERNAL)) {
    assert.ok(scripts.has(name), `${name} is exempted and is not an npm script`);
    assert.ok(why.length > 15, `${name} is exempted without a reason`);
  }
});

// --- scripts/*.mjs: the generated-page half, #478 (A6b) ---

test("the scripts/ population is real, so this cannot pass having examined nothing", () => {
  const scripts = commandScripts();
  // #478's own known census: 51 (the 50 command scripts at the time of writing, plus
  // `generate-commands-doc.mjs` itself). A floor, not a pin -- a legitimate new command script raises it;
  // this guard exists only to catch the discovery pattern breaking and matching nothing.
  assert.ok(scripts.length >= 40,
    `only found ${scripts.length} command script(s) under scripts/, fewer than the known census of ~51 -- `
    + "the entry-point-guard discovery is probably broken, not the population shrinking");
});

test("every script under scripts/ carries a `// command:` header", () => {
  const missing = commandScripts().filter((file) => {
    const text = readFileSync(join(REPO, "scripts", file), "utf8");
    return commandHeader(text) === null;
  });
  assert.deepEqual(missing, [],
    "these script(s) are real commands (they declare the entry-point guard `entry-points.test.ts` already "
    + "pins) and have no `// command: <description>` header, or the header is too weak (empty, one word, "
    + "under 15 characters) to count as documentation:\n"
    + missing.map((f) => `  scripts/${f}`).join("\n"));
});

// --- MUTATION: `commandHeader` must actually distinguish a real description from a weak one ---

test("MUTATION: a missing header is caught, not silently passed", () => {
  assert.equal(commandHeader("#!/usr/bin/env node\n// @ts-check\n// just a comment\n"), null);
});

test("MUTATION: a single-word header (`// command: runs`) is refused, not accepted as documentation", () => {
  assert.equal(commandHeader("// command: runs\n"), null);
});

test("MUTATION: a header under 15 characters is refused even with a space in it", () => {
  assert.equal(commandHeader("// command: do it\n"), null);
});

test("CONTROL: a real, multi-word description over 15 characters is accepted", () => {
  assert.equal(
    commandHeader("#!/usr/bin/env node\n// @ts-check\n// command: regenerate the report from the live corpus\n"),
    "regenerate the report from the live corpus");
});

test("MUTATION: a header more than HEADER_LINES down the file is not discovered -- it must be NEAR the "
  + "top, not merely present somewhere", () => {
  const farDown = "#!/usr/bin/env node\n// @ts-check\n" + "// filler line\n".repeat(20)
    + "// command: this is a real enough description but it is buried\n";
  assert.equal(commandHeader(farDown), null);
});
