/**
 * GENERATED FILES ARE NEVER TRACKED -- #459. #232's conflict resolution put `docs/coverage.md` back into
 * git's index and nothing in the tree noticed: #158's own `.gitignore` entry only stops a NEW `git add`,
 * it does nothing to a path the index already holds, and `packages/judge/src/coverage-doc.test.ts` only
 * checks what the generator PRODUCES -- never whether the result is tracked. Three guards, and none of
 * them asked the one question this file exists to ask.
 *
 * A tracked generated file is a conflict generator by construction: two branches that each regenerate the
 * same page each commit their own correct-for-their-own-tree snapshot, and the second to land conflicts
 * with the first in a file neither author wrote a line of.
 *
 * THE POPULATION IS DERIVED, NOT TYPED -- the same rule `dataset-paths.test.ts` and
 * `runs-write-guard.test.ts` already apply to their own discovery walks: a hand-written list of generated
 * paths goes stale the moment a script writes somewhere new. `docs/coverage.md` already carries a
 * machine-readable marker (an HTML comment, written by `generate-coverage-doc.ts`, opening with an
 * exclamation-and-two-dashes sequence immediately followed by the word GENERATED) for exactly this reason
 * -- so `generatedPaths()` collects that marker from file CONTENT across the whole tree rather than naming
 * `docs/coverage.md` a second time, and a future generated doc that reuses the convention is covered
 * automatically, with no list to update.
 *
 * NOTE FOR ANY FUTURE READER OF THIS FILE'S OWN SOURCE: the marker is never spelled out here as a
 * contiguous literal -- deliberately. Concatenating the opening sequence and the word GENERATED with real
 * whitespace between them, anywhere in this file's own prose, would make `generatedPaths()`'s walk match
 * THIS FILE and report it as an offender, since this file is itself tracked. Caught by running the test
 * against its own first draft, not by reasoning about it -- the exact self-referential collision this
 * repo's own EXEMPT-list tests have hit more than once tonight.
 *
 * A single generated SECTION inside an otherwise hand-written document is a different shape and stays out
 * of this population on purpose: `docs/known-gaps.md` says its index is "generated by
 * `scripts/known-gaps-index.mjs`" in plain prose, never in the HTML-comment form, because the file around
 * that index is hand-authored and belongs in git.
 *
 * ## `TRACKED_EXEMPT` -- a generated file allowed to stay tracked, NAMED, never omitted by silence
 *
 * #478 (A6b) needed `docs/commands.md` tracked and checked on GitHub, and its first draft did that by
 * leaving the marker out of the generated output -- which made this guard simply never SEE the file,
 * rather than know about it and permit it. That is the shape this repo has paid for four times: a guard
 * narrowed by omission rather than by a stated exception. So the file DOES carry the marker (it is a real
 * generated file) and is named here instead, with the reason, so the guard knows rather than not looking.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { npmCliInvocation } from "../../../../scripts/npm-cli-executable.mjs";
import { declareTreeWideGuard, walkTree } from "../../../../scripts/tree-wide-guard.mjs";

// #716/#704: this file's own population is the whole tracked tree, not one file -- declared here
// rather than inferred from its source, per ceo's ruling (2026-09-09) that the tree-wide-guard
// population must be derived from a real import, never from scanning source text.
declareTreeWideGuard();

const REPO_ROOT = fileURLToPath(new URL("../../../../", import.meta.url));
const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "runs", ".venv", "coverage", "backups"]);

const TRACKED_EXEMPT: Record<string, string> = {
  "docs/commands.md": "committed and checked deliberately (#478/A6b) -- a reader wants to browse the "
    + "command list on GitHub; checked against the tree by commands-documented.test.ts rather than left "
    + "untracked",
};

// #158's whole point is that `docs/coverage.md` is gitignored and exists ONLY when something has run
// `npm run docs:coverage` -- so a fresh checkout (a CI runner, a new clone) has no generated files on disk
// at all, and this file's floor assertion (below) would fail there having examined a population that is
// legitimately empty rather than broken. Regenerated once, at module load, the same discipline
// `coverage-doc.test.ts`'s own `regenerate()` uses -- so the known generated file is guaranteed present
// before any test in this file runs, in every environment.
const npxGen = npmCliInvocation("npx", ["tsx", "packages/lab/scripts/generate-coverage-doc.ts"]);
execFileSync(npxGen.command, npxGen.args, { cwd: REPO_ROOT, stdio: "pipe" });

/** `<` `!` `-` `-` optional whitespace `GENERATED`, built from parts so this file's OWN source -- which
 *  necessarily discusses the marker -- can describe it in prose without matching it. See the file header. */
const MARKER_OPEN = ["<", "!", "-", "-"].join("");
const GENERATED_MARKER = new RegExp(`${MARKER_OPEN}\\s*GENERATED\\b`);

/** Every file under REPO_ROOT, skipping the directories nothing here should read. */
function allRepoFiles(): string[] {
  const found: string[] = [];
  const walk = (dir: string) => {
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (SKIP_DIRS.has(entry.name)) continue;
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (entry.isFile()) found.push(path);
    }
  };
  walk(REPO_ROOT);
  return found;
}

/** How many leading lines count as "near the top" -- see `generatedPaths()`'s own comment for why this
 *  scan is restricted to them rather than the whole file. */
const HEADER_LINES = 10;

/**
 * Every file, repo-relative, that carries the generated-output marker NEAR ITS OWN TOP -- the population
 * this test governs. DERIVED from file CONTENT, not a hand-written list, and EXPORTED so a mutation check
 * or a neighbouring test can drive it directly.
 *
 * RESTRICTED TO THE FIRST FEW LINES, not a whole-file scan -- found by running this test against its own
 * first draft, which flagged `generate-coverage-doc.ts` (the WRITER) as generated output. The writer's own
 * source necessarily contains the marker text as a string literal, deep in a function body, because
 * embedding exactly that text in what it writes is its whole job; a whole-file scan cannot tell "this file
 * IS the marker" from "this file CONSTRUCTS the marker". Every real generated doc in this repo puts the
 * marker on one of its first few lines (`docs/coverage.md`'s is line 3, right after its H1), so restricting
 * the read to a header window keeps the true positive and drops the writer.
 */
export function generatedPaths(): string[] {
  const paths: string[] = [];
  for (const file of allRepoFiles()) {
    let header: string;
    try {
      header = readFileSync(file, "utf8").split("\n", HEADER_LINES).join("\n");
    } catch {
      continue; // a binary file, or one that vanished between the listing and the read
    }
    if (GENERATED_MARKER.test(header)) paths.push(relative(REPO_ROOT, file));
  }
  return paths.sort();
}

/**
 * The repo-relative paths git currently tracks -- one call, not one `git ls-files <path>` per candidate.
 * `env: sandboxGitEnv()` strips any inherited `GIT_*` redirect (`GIT_DIR` foremost) before spawning, per
 * this repo's own standing rule: a spawned `git` trusting an inherited environment once redirected a real
 * commit onto the primary checkout from inside a throwaway-repo test (`git-env.mjs`'s own header).
 */
function trackedPaths(): Set<string> {
  return new Set(walkTree({ kind: "all", roots: [] }).map((f) => f.path));
}

test("the discovery walk finds a realistic slice of the repo's own files", () => {
  const files = allRepoFiles();
  assert.ok(files.length > 300, `expected to discover the repo's files, found ${files.length}`);
});

test("this test file's own source does not match the marker it looks for -- the self-referential "
  + "collision named in its header comment, verified rather than merely claimed", () => {
  const self = fileURLToPath(import.meta.url);
  const content = readFileSync(self, "utf8");
  assert.equal(GENERATED_MARKER.test(content), false,
    "this file's own prose accidentally spelled out the marker as a contiguous literal");
});

test("no generated file is tracked in git", () => {
  const paths = generatedPaths();
  // A FLOOR, not just a walk: this must find the real generated file(s) on disk, or an empty population
  // would pass having examined nothing -- the exact shape #459's own row exists to close, and the one
  // this repo has shipped four times already for a different population.
  console.log(`generated-paths: checked ${paths.length} generated file(s): ${paths.join(", ") || "(none)"}`);
  assert.ok(paths.length > 0,
    "expected to find at least one generated file (docs/coverage.md) -- an empty population here would "
    + "make this test pass having verified nothing");

  const tracked = trackedPaths();
  // A SECOND floor, on the OTHER population this test enumerates: `git ls-files` failing or returning
  // nothing would make `offenders` trivially empty too, and this test would pass having verified nothing
  // about tracking at all -- the exact vacuity shape named at this file's own top, pointed at the
  // population `trackedPaths()` walks rather than the one `generatedPaths()` walks.
  assert.ok(tracked.size > 200, `only found ${tracked.size} tracked file(s) -- the ls-files scan is broken`);
  const offenders = paths.filter((p) => tracked.has(p) && !Object.hasOwn(TRACKED_EXEMPT, p));
  assert.deepEqual(offenders, [],
    "these generated file(s) are tracked in git and must not be -- untrack with `git rm --cached <path>` "
    + `and confirm .gitignore covers it, or add a reasoned entry to TRACKED_EXEMPT: ${offenders.join(", ")}`);
});

test("every TRACKED_EXEMPT entry is honest -- actually generated and actually tracked, so an exemption "
  + "cannot go stale or dead without this test seeing it", () => {
  const generated = new Set(generatedPaths());
  const tracked = trackedPaths();
  for (const [path, reason] of Object.entries(TRACKED_EXEMPT)) {
    assert.ok(reason.length > 0, `TRACKED_EXEMPT["${path}"] must state a reason`);
    assert.ok(generated.has(path),
      `TRACKED_EXEMPT names "${path}" but it does not carry the generated-file marker -- stale exemption, `
      + "remove it");
    assert.ok(tracked.has(path),
      `TRACKED_EXEMPT names "${path}" but it is not tracked in git -- unnecessary exemption, remove it`);
  }
});

test("docs/coverage.md is specifically among the discovered population -- names the known instance rather "
  + "than trusting the walk found SOMETHING", () => {
  assert.ok(generatedPaths().includes("docs/coverage.md"));
});

test("docs/known-gaps.md, whose index is generated in PROSE rather than the HTML-comment marker, is not "
  + "swept into the generated population -- a hand-written document with one generated section is a "
  + "different shape from a wholly generated file, and must not be untracked", () => {
  assert.ok(!generatedPaths().includes("docs/known-gaps.md"));
});
