/**
 * Write `docs/coverage.md` from `criterion-coverage.ts`.
 *
 * GENERATED, never hand-written, and that is the whole point. The facts already live in one place — which
 * criteria are assessed, what each one's boundary is, and whether a rule or a trained head decides it. A
 * prose page restating them would be a second copy, and this repo's most expensive recurring defect is one
 * fact written down twice with nothing comparing the two.
 *
 * `coverage-doc.test.ts` regenerates and diffs, so editing the source without regenerating fails the build
 * rather than quietly publishing a stale claim.
 *
 * The source file is the right home for accuracy — every entry carries the measurement and the reasoning
 * next to the code that uses it — and the wrong home for reading. This is the reading copy.
 */
import { writeFileSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { CRITERION_COVERAGE } from "../../judge/src/criterion-coverage.js";
import { WCAG_22_AA } from "@a11y-witness/evidence/wcag";
import { SCORED_CRITERIA } from "../../judge/src/coverage.js";

const REPO = resolve(import.meta.dirname, "../../..");
const OUT = resolve(REPO, "docs/coverage.md");

type Entry = { status: string; needs?: string[]; channels?: string[]; note?: string };
const criteria = new Map((WCAG_22_AA as { num: string; name: string; level: string }[])
  .map((c) => [c.num, c]));
const ownership = JSON.parse(
  readFileSync(resolve(REPO, "packages/lab/rule-ownership.json"), "utf8"),
).subtypes as Record<string, { decidedBy: string }>;

const byNumber = (a: string, b: string) => a.localeCompare(b, undefined, { numeric: true });
const entries = Object.entries(CRITERION_COVERAGE as Record<string, Entry>)
  .sort(([a], [b]) => byNumber(a, b));
const withStatus = (status: string) => entries.filter(([, e]) => e.status === status);

/**
 * Who answers this criterion, derived from two sources and never restated.
 *
 * The first version defaulted to "trained scorer" whenever a criterion had no entry in
 * `rule-ownership.json` — and printed exactly that for 1.4.2, whose own note in the same row says
 * "rule-only ... no head is trained on it". A criterion is absent from ownership either because a head
 * decides all of it OR because there is no head at all, and those are opposite answers. `SCORED_CRITERIA`
 * is what tells them apart: it lists the criteria the scorer has a head for.
 *
 * Caught by generating the page and reading it. A hand-written page would have carried the contradiction.
 */
function decidedBy(num: string): string {
  const mine = Object.entries(ownership).filter(([subtype]) => subtype.startsWith(`${num}:`));
  const hasHead = (SCORED_CRITERIA as readonly string[]).includes(num);
  if (mine.length === 0) return hasHead ? "trained scorer" : "deterministic rules";
  const parts = mine.map(([subtype, v]) => `\`${subtype.split(":")[1]}\` ${v.decidedBy}`);
  return hasHead ? `${parts.join("; ")}; rest: trained scorer` : parts.join("; ");
}

const escape = (text: string) => text.replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
const name = (num: string) => criteria.get(num)?.name ?? "(not in WCAG 2.2 AA)";
const level = (num: string) => criteria.get(num)?.level ?? "?";

function assessedTable(status: string): string {
  const rows = withStatus(status).map(([num, e]) =>
    `| **${num}** | ${name(num)} | ${level(num)} | ${decidedBy(num)} | ${escape(e.note ?? "")} |`);
  return ["| # | criterion | level | decided by | what is and is not covered |",
    "|---|---|---|---|---|", ...rows].join("\n");
}

function shortTable(status: string): string {
  const rows = withStatus(status).map(([num, e]) =>
    `| ${num} | ${name(num)} | ${level(num)} | ${(e.needs ?? []).join(" + ") || "—"} |`);
  return ["| # | criterion | level | would need |", "|---|---|---|---|", ...rows].join("\n");
}

const counts = Object.fromEntries(["assessed", "partial", "reachable", "out-of-scope"]
  .map((s) => [s, withStatus(s).length]));

const page = `# What this tool can and cannot detect

<!-- GENERATED by \`npm run docs:coverage\` from packages/judge/src/criterion-coverage.ts. Do not edit. -->

Every one of WCAG 2.2's ${entries.length} A and AA success criteria, and which of four states it is in.
Generated from \`criterion-coverage.ts\`, which is the source of truth and is pinned by tests against both
the WCAG list and what actually ships — so this page cannot drift from the code in either direction.

| state | count | meaning |
|---|---|---|
| **assessed** | ${counts.assessed} | a finding can be produced today |
| **partial** | ${counts.partial} | assessed, but a named failure mode of it is not covered |
| **reachable** | ${counts.reachable} | not built, and the evidence to build it exists or could be captured |
| **out of scope** | ${counts["out-of-scope"]} | not answerable by this tool at all |

**${counts.assessed + counts.partial} of ${entries.length} produce findings.** That is not a small number
for screen-reader evidence, and it is not a substitute for a rule scanner: the ${counts["out-of-scope"]}
out-of-scope criteria are mostly **visual**, which is exactly what axe-core is good at. Run both.

## Two things to read this table with

**"Assessed" means we have evidence and a decider — never that the answer is exact.** Where a deterministic
rule owns a subtype the answer is exact, measured at 0 false positives across 934 conformant records. Where
the trained scorer decides alone, the answer inherits the scorer's blind spots, and those are measured:
\`npm run scorer:shortcuts\` counts **225 features a head penalises for free** because they were 0 on every
one of its training examples. See [ADR 0015](./adr/0015-one-defect-per-page-taught-the-scorer-to-veto.md).

**A criterion can be part rule-decided and part model-decided**, and 1.1.1, 3.3.2 and 4.1.2 are. The
\`decided by\` column is per subtype for that reason.

## Assessed

${assessedTable("assessed")}

## Partial — assessed, with a named gap

These are the most useful rows in the table. Each names the failure mode it covers **and** the one it does
not, so a clean result is never mistaken for a clean page.

${assessedTable("partial")}

## Reachable — not built

The evidence exists, or could be captured with a probe. Nothing here is a research problem.

${shortTable("reachable")}

## Out of scope

Not answerable from what a screen reader produces. \`needs\` says what it would take instead — and
\`visual\` items are the rule layer's, which is why this tool ships axe-core alongside rather than
competing with it.

${shortTable("out-of-scope")}
`;

writeFileSync(OUT, page);
process.stdout.write(`wrote ${OUT} — ${entries.length} criteria, ${counts.assessed} assessed, `
  + `${counts.partial} partial\n`);
